import { expect, test } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';
import { evidencePath } from '../evidence-path';
import { installActivationProbe } from './command-activation-probe';
test.beforeEach(async ({ page }) => { await page.addInitScript(installActivationProbe); });
test.afterEach(async ({ page }) => {
    writeFileSync(evidencePath('library-actions-chain.json'), JSON.stringify(await page.evaluate(() => ({ events: window.__activation.events, active: document.activeElement?.outerHTML, dialog: document.querySelector('dialog')?.outerHTML, time: document.querySelector('[data-testid="model-time"]')?.textContent, status: document.querySelector('[data-testid="save-status"]')?.textContent })), null, 2));
});
test('invalid/cancelled imports preserve live state, names stay text, imports get new identities and delete requires confirmation', async ({ page }) => {
    await page.goto('/');
    await page.getByRole('button', { name: 'Start blank experiment', exact: true }).click();
    await page.getByRole('button', { name: '+1 s', exact: true }).click();
    await expect(page.getByTestId('model-time')).toHaveText('1.000 s');
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await page.getByLabel('Experiment name', { exact: true }).fill('<img src=x onerror=alert(1)>');
    await page.getByRole('button', { name: 'Save to Library', exact: true }).click();
    await expect(page.getByTestId('save-status')).toHaveText('Saved');
    const download = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export file', exact: true }).click();
    const file = await (await download).path();
    const data = readFileSync(file!);
    await page.getByRole('button', { name: 'Library', exact: true }).click();
    await expect(page.getByRole('dialog').locator('img')).toHaveCount(0);
    await page.getByLabel('Import .flyfork.json').setInputFiles({ name: 'bad.flyfork.json', mimeType: 'application/json', buffer: Buffer.from('{"version":99}') });
    await expect(page.getByRole('alert')).toBeVisible();
    await expect(page.getByTestId('model-time')).toHaveText('1.000 s');
    await page.getByLabel('Import .flyfork.json').setInputFiles({ name: 'saved.flyfork.json', mimeType: 'application/json', buffer: data });
    await page.getByRole('button', { name: 'Cancel import / load', exact: true }).click();
    await expect(page.getByTestId('model-time')).toHaveText('1.000 s');
    await expect(page.getByTestId('save-status')).toHaveText('Saved');
    await page.getByRole('button', { name: 'Library', exact: true }).click();
    await page.getByLabel('Import .flyfork.json').setInputFiles({ name: 'saved.flyfork.json', mimeType: 'application/json', buffer: data });
    await expect(page.getByRole('dialog')).toContainText('Validated experiment preview');
    await expect(page.locator('.preview-grid')).toContainText('import');
    await page.getByRole('button', { name: 'Load experiment', exact: true }).click();
    await expect(page.getByRole('dialog')).toBeHidden();
    await expect(page.getByTestId('save-status')).toHaveText('Unsaved history');
    await expect(page.getByTestId('model-time')).toHaveText('1.000 s');
    await expect(page.getByTestId('recorded-frontier')).toHaveText('Recorded to 1.000 s');
    await expect(page.getByTestId('replay-status')).toHaveText('Not checked');
    const importedDownload = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export file', exact: true }).click();
    const imported = JSON.parse(readFileSync((await (await importedDownload).path())!, 'utf8')).content;
    const original = JSON.parse(data.toString()).content;
    expect(imported.metadata.id).not.toBe(original.metadata.id);
    for (const key of ['seed', 'playhead', 'frontier', 'snapshots', 'records', 'live']) expect(imported[key]).toEqual(original[key]);
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await page.getByLabel('Experiment name', { exact: true }).fill('Imported copy');
    await page.getByRole('button', { name: 'Save to Library', exact: true }).click();
    await page.getByRole('button', { name: 'Library', exact: true }).click();
    await expect(page.locator('.library-list>li')).toHaveCount(2);
    await page.getByRole('button', { name: 'Rename Imported copy', exact: true }).click();
    await page.getByLabel('Experiment name', { exact: true }).fill('Renamed copy');
    await page.getByRole('button', { name: 'Save to Library', exact: true }).click();
    await page.getByRole('button', { name: 'Library', exact: true }).click();
    await page.getByLabel('Search local records').fill('Renamed');
    await expect(page.locator('.library-list>li')).toHaveCount(1);
    await page.getByRole('button', { name: 'Delete Renamed copy', exact: true }).click();
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.getByRole('button', { name: 'Library', exact: true }).click();
    await expect(page.locator('.library-list>li')).toHaveCount(1);
    await page.getByRole('button', { name: 'Delete Renamed copy', exact: true }).click();
    await page.getByRole('button', { name: 'Delete permanently', exact: true }).click();
    await expect(page.locator('.library-list>li')).toHaveCount(0);
    await page.getByLabel('Search local records').fill('');
    await expect(page.locator('.library-list>li')).toHaveCount(1);
    await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
    await expect(page.getByTestId('model-time')).toHaveText('1.000 s');
    await page.getByRole('button', { name: 'New experiment', exact: true }).click();
    await page.getByRole('button', { name: 'Create blank experiment', exact: true }).click();
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await expect(page.getByTestId('model-time')).toHaveText('1.000 s');
    await page.getByRole('button', { name: 'New experiment', exact: true }).click();
    await page.getByRole('button', { name: 'Create blank experiment', exact: true }).click();
    await page.getByRole('button', { name: 'Save and continue', exact: true }).click();
    await page.getByRole('button', { name: 'Save to Library', exact: true }).click();
    await expect(page.getByTestId('model-time')).toHaveText('0.000 s');
});
