import { evidencePath } from '../evidence-path';
import { axe } from './a11y';
import { test, expect } from '@playwright/test';
test('first visit offers a real guided experiment and a blank experiment', async ({ page }) => {
    await page.goto('/');
    await expect(page.getByRole('button', { name: 'Run guided experiment', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Start blank experiment', exact: true })).toBeVisible();
});
test('real guide, Library reload, 5 s / 12 s portable import, own-history replay and immutable drafts', async ({ page, browser }) => {
    test.setTimeout(90000);
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.setViewportSize({ width: 1672, height: 941 });
    await page.goto('/');
    await page.getByRole('button', { name: 'Run guided experiment', exact: true }).click();
    for (const name of ['Create same-state forks', 'Apply guided interventions', 'Compute to 12 s', 'Verify own histories', 'Finish guide']) {
        const button = page.getByRole('button', { name, exact: true });
        await expect(button).toBeEnabled();
        await button.click();
    }
    await expect(page.getByTestId('model-time')).toHaveText('12.000 s');
    await expect(page.getByTestId('comparison')).toHaveText('Branches differ');
    await expect(page.getByTestId('replay-status')).toHaveText('Matched');
    await expect(page.getByTestId('event-summary-A')).toContainText('3–8 s · Ended');
    const recorded = await page.getByTestId('event-summary-A').textContent();
    await page.getByLabel('Magnitude', { exact: true }).fill('0.3');
    await expect(page.getByTestId('event-summary-A')).toHaveText(recorded!);
    await page.screenshot({ path: evidencePath('triple-1672x941.png') });
    await page.getByLabel('Seek time seconds').fill('5');
    await page.getByRole('button', { name: 'Seek', exact: true }).click();
    await expect(page.getByTestId('model-time')).toHaveText('5.000 s');
    await expect(page.getByTestId('recorded-frontier')).toHaveText('Recorded to 12.000 s');
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await page.getByLabel('Experiment name', { exact: true }).fill('12 s record, 5 s view');
    await page.getByRole('button', { name: 'Save to Library', exact: true }).click();
    await expect(page.getByTestId('save-status')).toHaveText('Saved');
    await page.getByRole('button', { name: 'Library', exact: true }).click();
    await expect(page.getByRole('heading', { name: '12 s record, 5 s view', exact: true })).toBeVisible();
    await page.screenshot({ path: evidencePath('library-1672.png') });
    await page.reload();
    await page.getByRole('button', { name: 'Open Library or import', exact: true }).click();
    await page.getByRole('button', { name: 'Preview 12 s record, 5 s view', exact: true }).click();
    await expect(page.getByText('Not checked · recomputation required', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Load experiment', exact: true }).click();
    await expect(page.getByTestId('model-time')).toHaveText('5.000 s');
    await expect(page.getByTestId('recorded-frontier')).toHaveText('Recorded to 12.000 s');
    await expect(page.getByTestId('replay-status')).toHaveText('Not checked');
    const poses = await page.locator('.branch-window').evaluateAll(nodes => nodes.map(n => [n.getAttribute('data-x'), n.getAttribute('data-y')]));
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export file', exact: true }).click();
    const download = await downloadPromise;
    const path = evidencePath('round-trip.flyfork.json');
    await download.saveAs(path);
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } }), imported = await context.newPage();
    await imported.goto(new URL('/', page.url()).href);
    await imported.getByRole('button', { name: 'Open Library or import', exact: true }).click();
    await imported.getByLabel('Import .flyfork.json').setInputFiles(path);
    await expect(imported.getByRole('heading', { name: 'Validated experiment preview', exact: true })).toBeVisible();
    await axe(imported, 'import-preview');
    await imported.screenshot({ path: evidencePath('import-preview.png') });
    await imported.getByRole('button', { name: 'Load experiment', exact: true }).click();
    await expect(imported.getByTestId('model-time')).toHaveText('5.000 s');
    await expect(imported.getByTestId('recorded-frontier')).toHaveText('Recorded to 12.000 s');
    await expect(imported.getByTestId('replay-status')).toHaveText('Not checked');
    expect(await imported.locator('.branch-window').evaluateAll(nodes => nodes.map(n => [n.getAttribute('data-x'), n.getAttribute('data-y')]))).toEqual(poses);
    await imported.getByRole('button', { name: 'Replay check', exact: true }).click();
    await expect(imported.getByTestId('replay-status')).toHaveText('Matched');
    await imported.getByLabel('Seek time seconds').fill('12');
    await imported.getByRole('button', { name: 'Seek', exact: true }).click();
    await expect(imported.getByTestId('model-time')).toHaveText('12.000 s');
    await imported.getByRole('button', { name: 'Replay check', exact: true }).click();
    await expect(imported.getByTestId('replay-status')).toHaveText('Matched');
    await imported.getByRole('button', { name: 'Compare states', exact: true }).click();
    await expect(imported.getByTestId('comparison')).toHaveText('Branches differ');
    await imported.screenshot({ path: evidencePath('triple-1440x900.png') });
    await context.close();
    expect(errors).toEqual([]);
});
