import { evidencePath } from '../evidence-path';
import { writeFileSync } from 'node:fs';
import { test, expect } from '@playwright/test';
test('production save, reload, portable import and fresh own-history replay', async ({ page, browser, browserName }, testInfo) => {
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto('/');
    await page.getByRole('button', { name: 'Run guided experiment', exact: true }).click();
    for (const name of ['Create same-state forks', 'Apply guided interventions', 'Compute to 12 s', 'Verify own histories', 'Finish guide'])
        await page.getByRole('button', { name, exact: true }).click();
    await expect(page.getByTestId('replay-status')).toHaveText('Matched');
    await expect(page.getByTestId('comparison')).toHaveText('Branches differ');
    const selectTargets = await page.locator('select:visible').evaluateAll(elements => elements.map(element => ({ label: element.getAttribute('aria-label') ?? element.id, height: element.getBoundingClientRect().height })));
    writeFileSync(evidencePath(`${browserName}-select-targets.json`), JSON.stringify(selectTargets, null, 2));
    for (const target of selectTargets)
        expect(target.height, `${browserName} select ${target.label}`).toBeGreaterThanOrEqual(44);
    await page.getByLabel('Seek time seconds').fill('5');
    await page.getByRole('button', { name: 'Seek', exact: true }).click();
    await expect(page.getByTestId('model-time')).toHaveText('5.000 s');
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await page.getByLabel('Experiment name', { exact: true }).fill(`${browserName} record`);
    await page.getByRole('button', { name: 'Save to Library', exact: true }).click();
    await expect(page.getByTestId('save-status')).toHaveText('Saved');
    await page.reload();
    await page.getByRole('button', { name: 'Open Library or import', exact: true }).click();
    await page.screenshot({ path: evidencePath(`${browserName}-library.png`) });
    await page.getByRole('button', { name: `Preview ${browserName} record`, exact: true }).click();
    await page.getByRole('button', { name: 'Load experiment', exact: true }).click();
    await expect(page.getByTestId('model-time')).toHaveText('5.000 s');
    await expect(page.getByTestId('recorded-frontier')).toHaveText('Recorded to 12.000 s');
    await expect(page.getByTestId('replay-status')).toHaveText('Not checked');
    const pending = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export file', exact: true }).click();
    const downloaded = await pending;
    const file = testInfo.outputPath('record.flyfork.json');
    await downloaded.saveAs(file);
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } }), imported = await context.newPage();
    await imported.goto(new URL('/', page.url()).href);
    await imported.getByRole('button', { name: 'Open Library or import', exact: true }).click();
    await imported.getByLabel('Import .flyfork.json').setInputFiles(file);
    await expect(imported.getByRole('dialog')).toContainText('Not checked');
    await imported.screenshot({ path: evidencePath(`${browserName}-import.png`) });
    await imported.getByRole('button', { name: 'Load experiment', exact: true }).click();
    await expect(imported.getByTestId('model-time')).toHaveText('5.000 s');
    await imported.getByRole('button', { name: 'Replay check', exact: true }).click();
    await expect(imported.getByTestId('replay-status')).toHaveText('Matched');
    await imported.getByLabel('Seek time seconds').fill('12');
    await imported.getByRole('button', { name: 'Seek', exact: true }).click();
    await expect(imported.getByTestId('model-time')).toHaveText('12.000 s');
    await imported.getByRole('button', { name: 'Replay check', exact: true }).click();
    await expect(imported.getByTestId('replay-status')).toHaveText('Matched');
    await imported.screenshot({ path: evidencePath(`${browserName}-triple.png`) });
    writeFileSync(evidencePath(`${browserName}-smoke.json`), JSON.stringify({ browser: browser.version(), browserName, headless: true, errors, frontier: await imported.getByTestId('recorded-frontier').textContent(), replay: await imported.getByTestId('replay-status').textContent(), webglErrors: await imported.getByText(/WebGL unavailable|WebGL context lost/).count() }, null, 2));
    await context.close();
    expect(errors).toEqual([]);
});
