import { useState } from 'react';
import type { LabView } from '../worker-protocol/protocol';
export function ModelDetails({ dataset }: {
    dataset: LabView['dataset'] | undefined;
}) {
    const [group, setGroup] = useState('all');
    const selected = dataset?.groups.find(g => g.name === group);
    const cells = dataset?.cells.filter((_, i) => !selected || selected.indices.includes(i)) ?? [];
    return <div className="model-details"><p>Real MaleCNS source connections are used in the selected subgraph. Neuron dynamics, sensory input and the body decoder are model assumptions. This is not a whole brain.</p><ul><li>LIF state, sensory input, PN readout and body movement are separate layers.</li><li>PN means projection neuron, not motor neuron. The readout drives an engineered body model.</li><li>The speed cap and excluded external connections limit interpretation.</li><li>Replay checks numerical reproduction; it does not validate animal biology.</li></ul><p>Current dataset: <strong>{dataset?.title}</strong> · {dataset?.neuronCount} cells · {dataset?.edgeCount.toLocaleString()} directed edges.</p><p>Model: <code>{dataset?.model}</code></p><p>Dataset SHA-256: <code>{dataset?.hash}</code></p><label>Inspect source group<select value={group} onChange={e => setGroup(e.target.value)}><option value="all">All source cells</option>{dataset?.groups.map(g => <option key={g.name}>{g.name}</option>)}</select></label><div className="source-table" role="region" tabIndex={0} aria-label="Source cell table"><table><caption>Read-only source identities · {cells.length} cells</caption><thead><tr><th>Source ID</th><th>Type</th><th>Side</th><th>Sign</th></tr></thead><tbody>{cells.map(c => <tr key={c.id}><td>{c.id}</td><td>{c.type}</td><td>{c.side}</td><td>{c.sign > 0 ? 'Excitatory (+)' : 'Inhibitory (−)'}</td></tr>)}</tbody></table></div><details><summary>Directed connections and model parameters</summary><p>Each row sums raw source synapses between type/side groups. Direction is from → to; source neurotransmitter prediction determines the sign. Count is not a physiological conductance. Self-edges are retained.</p><table><caption>Actual group totals</caption><thead><tr><th>From</th><th>To</th><th>Raw synapses</th><th>Sign</th></tr></thead><tbody>{dataset?.connections.map(c => <tr key={`${c.from}-${c.to}`}><td>{dataset.groups[c.from].name}</td><td>{dataset.groups[c.to].name}</td><td>{c.synapses}</td><td>{c.sign > 0 ? '+' : '−'}</td></tr>)}</tbody></table><p>dt 0.1 ms; membrane/synapse time constants 20/5 ms; decoder divisor 400; speed cap 6 model units/s. Antenna samples drive independent PRNG streams. Branch names do not change the seed. Suppression and odor gain are bounded, timed model operators.</p><p>ORN side describes root entry; PN side describes soma side. This is not a claim about all output arborization. External connections were excluded to form the selected circuit.</p></details><p>Source: <a href="https://male-cns.janelia.org/download/" target="_blank" rel="noreferrer">MaleCNS v1.0 / FlyEM collaboration</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0 data</a>. Synthetic fixture is an explicitly separate test network.</p></div>;
}
