import { useState } from 'react';
import { Dialog } from './Dialog';
import type { useWorkspace } from './use-workspace';
import type { useLab } from './use-lab';
import { ModelDetails } from './ModelDetails';
const guideTitles = ['Start from the same state', 'Record bounded interventions', 'Compare at the same model time', 'Recompute each own history', 'Keep this experiment'];
const guideCopy = [
    'Compute seed 42 to 2 s, capture its complete state, then create Original / Fork A / Fork B. No prepared route is played.',
    'Fork A: suppression 1 on the real left DM1 projection neuron. Fork B: odor gain 0. Both events run from 3 s up to, but excluding, 8 s. Original stays the control.',
    'Compute all three branches to 12 s. Different paths and small or zero effects are valid outcomes. PN activity, the speed cap and actual displacement are separate measurements.',
    'Replay recomputes each branch from its own start and recorded events. Branches differ and Replay Matched can both be correct. This checks numerical reproduction, not animal biology.',
    'Save creates a named local Library record. Export creates a portable .flyfork.json file. Storage belongs to this browser, profile and address; it is not a cloud backup.'
];
export function WorkspaceDialogs({ ws, lab }: {
    ws: ReturnType<typeof useWorkspace>;
    lab: ReturnType<typeof useLab>;
}) {
    const [dataset, setDataset] = useState<'malecns' | 'synthetic'>('malecns');
    const busy = ws.io || lab.busy || ws.guideBusy;
    if (!ws.modal)
        return null;
    const titles = { welcome: 'A small circuit. Three possible futures.', library: 'Local Library', save: ws.renameEntry ? 'Rename experiment' : ws.saveCopy ? 'Save as copy' : 'Save experiment', unsaved: 'Keep your unsaved experiment?', preview: ws.preview?.source === 'recovery' ? 'Recover last durable record' : 'Validated experiment preview', delete: 'Delete Library record?', new: 'New experiment', guide: guideTitles[ws.guideStep], model: 'Model & limitations' };
    return <Dialog key={ws.modal} title={titles[ws.modal]} onClose={ws.close} returnFocus={ws.opener.current} kind={ws.modal}>
        {lab.failed && lab.error && <p role="alert" className="dialog-error">{lab.error}</p>}
        {ws.problem && <p role="alert" className="dialog-error">{ws.problem}</p>}
        {ws.io && <p role="status">{ws.savePhase === 'waiting' ? 'Waiting for the current recovery record…' : ws.savePhase === 'saving' ? 'Saving to local Library…' : 'Preparing a consistent record…'}</p>}
        {ws.modal === 'welcome' && <><p>Pause one simulated state, apply limited interventions, and compare three futures. The connections come from a real selected fly circuit; its dynamics and body model are assumptions.</p><div className="dialog-actions"><button className="button primary" disabled={busy} onClick={() => void ws.start('malecns', true)}>Run guided experiment</button><button className="button" disabled={busy} onClick={() => void ws.start(lab.view?.dataset.kind ?? 'malecns')}>Start blank experiment</button></div><p className="caption">About one minute · calculated live · skippable</p><button className="button" disabled={ws.io} onClick={() => void ws.openLibrary()}>Open Library or import</button>{ws.recovery?.file && <section className="recovery-offer"><h3>Last durable recovery available</h3><p>{ws.recovery.entry?.name} · view {(ws.recovery.entry!.playhead / 10000).toFixed(2)} s · recorded to {(ws.recovery.entry!.frontier / 10000).toFixed(2)} s</p><p>Only data through this successful save can be recovered. Later unsaved work may be lost.</p><button className="button" disabled={busy} onClick={() => void ws.previewFile(ws.recovery!.file!, 'recovery')}>Review recovery</button></section>}</>}
        {ws.modal === 'library' && <><p>Records stay in this browser / profile / address. There is no cloud backup. Export important experiments. A different host, protocol or port has a separate Library.</p><p className="caption">Up to 50 records / 128 MiB · files up to 16 MiB · no automatic record deletion</p><div className="library-tools"><label>Search local records<input type="search" value={ws.search} onChange={e => void ws.filter(e.target.value)}/></label><label className="file-picker">Import .flyfork.json<input type="file" accept=".flyfork.json,application/json" disabled={ws.io} onChange={e => {
                const file = e.target.files?.[0];
                if (file)
                    void ws.importFile(file);
                e.target.value = '';
            }}/></label></div><p role="status">{ws.storageMessage}</p>{ws.rows.length ? <ul className="library-list">{ws.rows.map(row => <li key={row.id}><h3>{row.name}</h3><p>{row.dataset === 'malecns' ? 'MaleCNS selected subgraph' : 'Synthetic fixture'} · {row.branches} branches · {row.model}</p><p>View {(row.playhead / 10000).toFixed(2)} s · recorded to {(row.frontier / 10000).toFixed(2)} s · saved {new Date(row.savedAt).toLocaleString()} · {(row.bytes / 1048576).toFixed(2)} MiB</p><div className="dialog-actions"><button className="button primary" disabled={busy} aria-label={`Preview ${row.name}`} onClick={() => void ws.loadEntry(row)}>Preview</button><button className="button" disabled={busy} aria-label={`Rename ${row.name}`} onClick={() => ws.rename(row)}>Rename</button><button className="button" disabled={busy} aria-label={`Export ${row.name}`} onClick={() => void ws.exportFile(row)}>Export</button><button className="button danger" disabled={busy} aria-label={`Delete ${row.name}`} onClick={() => ws.confirmDelete(row)}>Delete</button></div></li>)}</ul> : <div className="library-empty"><span aria-hidden="true">⑂</span><h3>No matching local records</h3><p>Save an experiment or import a file to keep its recorded history here.</p></div>}{ws.recovery?.file && <section className="recovery-offer"><h3>Separate recovery slot</h3><p>Last durable record: {new Date(ws.recovery.entry!.savedAt).toLocaleString()}, view {(ws.recovery.entry!.playhead / 10000).toFixed(2)} s, frontier {(ws.recovery.entry!.frontier / 10000).toFixed(2)} s.</p><button className="button" disabled={busy} onClick={() => void ws.previewFile(ws.recovery!.file!, 'recovery')}>Review recovery</button></section>}</>}
        {ws.modal === 'save' && <form onSubmit={e => { e.preventDefault(); void ws.save(); }}><label>Experiment name<input autoFocus maxLength={100} value={ws.formName} onChange={e => ws.setFormName(e.target.value)} required/></label><p>The viewing cursor, recorded frontier, full states and immutable event logs are saved together.</p><div className="dialog-actions"><button className="button primary" disabled={!ws.canSave} type="submit">Save to Library</button><button className="button" type="button" disabled={ws.io} onClick={() => ws.openSave(true)}>Save as copy</button><button className="button" type="button" onClick={ws.close}>Cancel</button></div></form>}
        {ws.modal === 'unsaved' && <><p>This experiment has physical history that is not in its named Library record. Recovery is separate and may be older.</p><div className="dialog-actions"><button className="button primary" disabled={ws.io || !ws.available || lab.failed} onClick={() => ws.openSave()}>Save and continue</button><button className="button danger" disabled={ws.io} onClick={() => void ws.discard()}>Discard and continue</button><button className="button" onClick={ws.close}>Cancel</button></div></>}
        {ws.modal === 'preview' && ws.preview && <><h3>{ws.preview.metadata.name}</h3><dl className="preview-grid"><dt>Source</dt><dd>{ws.preview.source}</dd><dt>Dataset / model</dt><dd>{ws.preview.client.view!.dataset.title} / {ws.preview.client.view!.dataset.model}</dd><dt>Viewing cursor</dt><dd>{(ws.preview.client.view!.original.tick / 10000).toFixed(3)} s</dd><dt>Recorded frontier</dt><dd>{(ws.preview.client.view!.highWater / 10000).toFixed(3)} s</dd><dt>Fork / events</dt><dd>{ws.preview.client.view!.forkTick === null ? 'No fork' : '3 branches'} / {ws.preview.client.view!.events.length} recorded events</dd><dt>Saved</dt><dd>{new Date(ws.preview.metadata.savedAt).toLocaleString()}</dd><dt>Source runtime</dt><dd>{ws.preview.metadata.runtime}</dd><dt>Replay in this session</dt><dd>Not checked · recomputation required</dd></dl><p>Structure, supported identities, buffer limits and SHA-256 were checked. This is not a publisher signature or biological validation. Different runtimes may differ.</p>{ws.preview.source === 'recovery' && <p>Recovery opens paused at the last durable cursor, with its recorded frontier. Later unsaved changes cannot be recovered.{lab.view && lab.view.highWater > ws.preview.client.view!.highWater && ` This session computed to ${(lab.view.highWater / 10000).toFixed(3)} s; recovery ends at ${(ws.preview.client.view!.highWater / 10000).toFixed(3)} s. ${((lab.view.highWater - ws.preview.client.view!.highWater) / 10000).toFixed(3)} s of later computed history will be lost.`}</p>}<div className="dialog-actions"><button className="button primary" disabled={busy} onClick={() => void ws.acceptPreview()}>Load experiment</button><button className="button" onClick={ws.close}>Cancel import / load</button></div></>}
        {ws.modal === 'delete' && <><p>Delete “{ws.deleteEntry?.name}” from this Library? This cannot be undone. Its live simulation, other records and recovery slot are preserved.</p><div className="dialog-actions"><button className="button danger" disabled={ws.io} onClick={() => void ws.remove()}>Delete permanently</button><button className="button" onClick={ws.close}>Cancel</button></div></>}
        {ws.modal === 'new' && <><p>Create a fresh paused experiment without reloading. The existing experiment stays active until this transition succeeds.</p><label>Dataset<select value={dataset} onChange={e => setDataset(e.target.value as typeof dataset)}><option value="malecns">MaleCNS selected subgraph</option><option value="synthetic">Synthetic test fixture</option></select></label><div className="dialog-actions"><button className="button primary" disabled={busy} onClick={() => void ws.start(dataset)}>Create blank experiment</button><button className="button" disabled={busy} onClick={() => void ws.start('malecns', true)}>Run guided experiment</button><button className="button" onClick={ws.close}>Cancel</button></div></>}
        {ws.modal === 'guide' && <><ol className="guide-progress" aria-label="Guide progress">{['Snapshot', 'Intervene', 'Compare', 'Replay', 'Keep'].map((label, i) => <li key={label} aria-current={i === ws.guideStep ? 'step' : undefined} data-complete={i < ws.guideStep}><span>{i < ws.guideStep ? '✓' : i + 1}</span>{label}</li>)}</ol><p className="eyebrow">Step {ws.guideStep + 1} of 5 · calculated live</p><p>{guideCopy[ws.guideStep]}</p>{ws.guideStep >= 3 && <p>Calculated comparison: {lab.view?.comparisons ? lab.view.comparisons.A.equal && lab.view.comparisons.B.equal ? 'No numeric difference' : 'Branches differ' : 'Not checked'}. Own-history replay: {lab.view?.replay.status ?? 'Not checked'}.</p>}{ws.guideBusy && <p>Waiting for the real Worker acknowledgement… {lab.view?.job ? `${lab.view.job.type}: ${(lab.view.job.progress / 10000).toFixed(1)} s` : ''}</p>}<div className="dialog-actions"><button className="button primary" disabled={busy} onClick={() => void ws.nextGuide()}>{['Create same-state forks', 'Apply guided interventions', 'Compute to 12 s', 'Verify own histories', 'Finish guide'][ws.guideStep]}</button><button className="button" onClick={ws.close}>Exit guide</button></div></>}
        {ws.modal === 'model' && <ModelDetails dataset={lab.view?.dataset}/>}
    </Dialog>;
}
