import { createServer } from 'node:http';
import { readFileSync,writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { randomUUID,createHash } from 'node:crypto';
import { reserve,inside } from './r3-output.mjs';
import { verificationRoot,admitEnvironment } from './verification-paths.mjs';
const [engine,scope,baseURL,action] = process.argv.slice(2);
if(process.argv.length!==6 || !['chrome','webkit','firefox'].includes(engine) || !['full','smoke','transaction','focus','focus-red','import'].includes(scope) || !['collect','run'].includes(action)) throw Error('engine scope loopbackURL collect|run required');
admitEnvironment(process.env);
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end('<!doctype html><title>FlyFork isolated transaction harness</title>');});
await new Promise((ok,fail)=>{server.once('error',fail);server.listen(0,'127.0.0.1',ok)});
const transactionURL='http://127.0.0.1:'+server.address().port+'/';
const run=reserve(verificationRoot(),`runtime-${engine}-${scope}-${action}-${Date.now()}-${randomUUID().slice(0,8)}`);
const put=(name,value)=>writeFileSync(inside(run,resolve(run,name)),JSON.stringify(value,null,2),{flag:'wx'});
const hash=f=>createHash('sha256').update(readFileSync(f)).digest('hex');
put('plan.json',{engine,scope,baseURL,transactionURL,action,retry:0,workers:1,timeout:60000,maxFailures:3,configSha256:hash('playwright.runtime.config.mjs'),testSource:'current source manifest; test IDs separately collected',target:scope==='transaction'?'separate empty transaction server, not production runtime':'explicit loopback Nginx runtime; image identity supplied with campaign report',productionCSP:'bypass=false; transaction project uses a separate empty test origin',identity:{engine,node:process.version,platform:process.platform,arch:process.arch}});
const args=['node_modules/@playwright/test/cli.js','test','--config=playwright.runtime.config.mjs',...(action==='collect'?['--list']:[])];
put('command.json',{exe:process.execPath,args,node:process.version,platform:process.platform,arch:process.arch,started:new Date().toISOString()});
const env={...process.env,FLYFORK_EVIDENCE_DIR:run};
// Validate the effective explicit config before Playwright can clean outputDir.
process.env.FLYFORK_EVIDENCE_DIR=run;
const config=(await import('../playwright.runtime.config.mjs')).default;
if(config.workers!==1 || config.retries!==0 || resolve(config.outputDir)!==resolve(run,'test-results') || config.webServer) throw Error('WP3 effective config rejected');
for(const project of config.projects) if(project.use.bypassCSP && !project.name.endsWith('-transaction-harness')&&!project.name.endsWith('-isolated-transaction-server')) throw Error('Unexpected CSP bypass');
put('effective-config.json',config);
console.log('START '+run);
const start=performance.now();
const child=await new Promise(done=>{const p=spawn(process.execPath,args,{env,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';p.stdout.on('data',b=>stdout+=b);p.stderr.on('data',b=>stderr+=b);p.on('error',error=>done({status:1,error,stdout,stderr}));p.on('close',(status,signal)=>done({status,signal,stdout,stderr}));});
server.closeAllConnections();await new Promise(r=>server.close(r));
writeFileSync(inside(run,resolve(run,'stdout.log')),child.stdout??'',{flag:'wx'});writeFileSync(inside(run,resolve(run,'stderr.log')),child.stderr??'',{flag:'wx'});
put('result.json',{code:child.status,signal:child.signal,error:child.error?.message,elapsedMs:performance.now()-start,finished:new Date().toISOString()});
console.log('END '+child.status+' '+run);process.exitCode=child.status??1;
