import {chromium,expect}from'@playwright/test';import{readFileSync,writeFileSync}from'node:fs';import{resolve}from'node:path';import{gzipSync}from'node:zlib';import{randomUUID,createHash}from'node:crypto';import{reserve,inside}from'./r3-output.mjs';import{verificationRoot,admitEnvironment}from'./verification-paths.mjs';import{installPerfProbe}from'./runtime-perf-probe.mjs';
admitEnvironment(process.env);const [baseURL,distArg]=process.argv.slice(2);if(process.argv.length!==4)throw Error('loopbackURL exported-active-dist required');if(new URL(baseURL).hostname!=='127.0.0.1')throw Error('Loopback required');
const out=reserve(verificationRoot(),`runtime-save-${Date.now()}-${randomUUID().slice(0,8)}`),file=n=>inside(out,resolve(out,n)),put=(n,v)=>writeFileSync(file(n),JSON.stringify(v,null,2),{flag:'wx'});
put('plan.json',{baseURL,headless:false,channel:'installed Google Chrome',viewport:{width:1672,height:941},dpr:1,seed:42,quality:'Standard',camera:'unchanged product camera',speed:2,warmup:'four common model seconds after Resume',sample:'first >=200 actual GL frames after warmup',thresholds:{fps:55,p95Ms:20,commonModelSecondsPerSecond:1},saveScenarios:['paused12','paused120','running12','running118'],onceEach:true,bypassCSP:false,observerCost:'JS metadata wrappers on Worker/IDB/GL; one rAF poll, GPU queries and longtask observer; not overhead-free. No profiler/video or trace during timed samples.',displayRefresh:'OS read unavailable; rAF cadence observed separately, not asserted physical refresh',thermal:'pmset read unavailable; no setting changed'});put('command.json',{argv:process.argv,node:process.version,platform:process.platform,arch:process.arch,host:'Physical host details recorded separately by campaign; no inferred refresh/thermal'});
const browser=await chromium.launch({channel:'chrome',headless:false});const report={browser:browser.version(),scenarios:[],failures:[],requests:[],normal:null};
const snap=p=>p.evaluate(()=>window.__wp3perf.snapshot()),click=(p,name)=>p.getByRole('button',{name,exact:true}).click();
const summary=a=>{const s=a.filter(Number.isFinite).sort((a,b)=>a-b);return{n:s.length,mean:s.reduce((a,b)=>a+b,0)/s.length,p95:s[Math.floor(s.length*.95)]??null,max:s.at(-1)??null}};
for(const label of ['paused12','paused120','running12','running118']){
 const ctx=await browser.newContext({baseURL,viewport:{width:1672,height:941},deviceScaleFactor:1,bypassCSP:false});const p=await ctx.newPage();p.setDefaultTimeout(60000);await p.addInitScript(installPerfProbe);const entry={label,errors:[]};p.on('pageerror',e=>entry.errors.push(e.message));
 p.on('response',async r=>{try{if(label==='paused12')report.requests.push({url:r.url(),type:r.request().resourceType(),status:r.status(),headers:r.headers(),sizes:await r.request().sizes()})}catch{}});
 try{
  await p.goto('/');await p.bringToFront();for(const name of ['Run guided experiment','Create same-state forks','Apply guided interventions','Compute to 12 s','Verify own histories','Finish guide'])await click(p,name);await expect(p.getByTestId('model-time')).toHaveText('12.000 s');entry.ready=await snap(p);
  if(label==='paused120'||label==='running118'){
   await p.getByLabel('Simulation speed').selectOption('2');await click(p,'Resume');
   if(label==='paused120'){
    await p.waitForFunction(()=>window.__wp3perf.snapshot().tick>=160000);const before=await snap(p);const start=await p.evaluate(()=>({time:performance.now(),n:window.__wp3perf.frames.length,tick:window.__wp3perf.snapshot().tick}));
    await p.waitForFunction(n=>window.__wp3perf.frames.length>=n+201,start.n,{timeout:30000});const end=await p.evaluate(()=>({time:performance.now(),data:window.__wp3perf.snapshot()}));const sample=end.data.frames.slice(start.n,start.n+201),frameSummary=summary(sample.slice(1).map(f=>f.intervalMs));
    report.normal={start,endTime:end.time,before,after:end.data,sample,frameSummary,fps:1000/frameSummary.mean,cpuDrawSpan:summary(sample.map(f=>f.cpuDrawSpanMs)),gpu:summary(sample.filter(f=>!f.disjoint).map(f=>f.gpuMs)),commonModelSecondsPerSecond:(end.data.tick-start.tick)/10000/((end.time-start.time)/1000)};
   }
   await p.waitForFunction(t=>window.__wp3perf.snapshot().tick>=t,label==='paused120'?1200000:1180000,{timeout:65000});if(label==='paused120')await expect(p.getByTestId('run-status')).toHaveText('Paused');
  }else if(label==='running12')await click(p,'Resume');
  entry.before=await snap(p);await p.evaluate(l=>window.__wp3perf.mark('save-start-'+l),label);
  await click(p,'Save');await p.getByLabel('Experiment name',{exact:true}).fill('R1 '+label);await click(p,'Save to Library');await expect(p.getByRole('dialog')).toBeHidden();if(label.startsWith('running')) await expect(p.getByText('Saved to local Library.',{exact:true})).toBeVisible(); else await expect(p.getByTestId('save-status')).toHaveText('Saved');
  await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));entry.after=await snap(p);entry.events=entry.after.events.slice(entry.before.events.length);const start=entry.events.find(e=>e.type==='mark'),finish=entry.events.at(-1).time;
  entry.saveFrames=entry.after.frames.filter(f=>f.time>=start.time&&f.time<=finish);entry.saveRaf=entry.after.raf.filter(f=>f.time>=start.time&&f.time<=finish);entry.saveLongTasks=entry.after.longTasks.filter(x=>x.start+x.duration>=start.time&&x.start<=finish);
  entry.summary={actualDrawnFrames:entry.saveFrames.length,frame:summary(entry.saveFrames.map(f=>f.intervalMs)),raf:summary(entry.saveRaf.map(f=>f.interval)),cpuDrawSpan:summary(entry.saveFrames.map(f=>f.cpuDrawSpanMs)),longTasks:entry.saveLongTasks};
  const submits=entry.events.filter(e=>e.type==='click'&&e.name==='Save to Library');expect(submits).toHaveLength(1);expect(submits[0].trusted).toBe(true);
  const transactions=entry.events.filter(e=>e.type==='transaction'&&e.mode==='readwrite'&&e.stores.includes('entries')&&e.stores.includes('payloads'));expect(transactions).toHaveLength(1);expect(entry.events.filter(e=>e.type==='transaction-complete'&&e.id===transactions[0].id)).toHaveLength(1);
  const stored=await p.evaluate(async name=>{const db=await new Promise((ok,fail)=>{const r=indexedDB.open('flyfork-library');r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)});try{return await new Promise((ok,fail)=>{const t=db.transaction(['entries','payloads'],'readonly');const e=t.objectStore('entries').getAll(),f=t.objectStore('payloads').getAll();t.oncomplete=()=>{const entry=e.result.find(x=>x.name===name);ok({entry,file:f.result.find(x=>x.id===entry.id).file})};t.onerror=()=>fail(t.error)})}finally{db.close()}},'R1 '+label);
  const exports=await p.evaluate(()=>window.__wp3perf.exports);const ack=exports.find(e=>e.file===stored.file);expect(ack,'Stored payload is exactly an observed export ACK').toBeDefined();const captured=JSON.parse(stored.file).content;
  expect([stored.entry.playhead,stored.entry.frontier]).toEqual([captured.playhead,captured.frontier]);
  entry.contract={nativeSubmissions:1,namedCommits:1,ack:{sessionId:ack.sessionId,requestId:ack.requestId},stored:stored.entry,payloadSha256:createHash('sha256').update(stored.file).digest('hex'),liveTickAtCommit:entry.events.find(e=>e.type==='transaction-complete'&&e.id===transactions[0].id).tick};
  // Navigation disposes the live Worker. A sampled Running flag can already be
  // obsolete at the 120 s horizon; no extra Pause is needed to reopen the commit.
  await p.reload();await click(p,'Open Library or import');await click(p,'Preview R1 '+label);await click(p,'Load experiment');await expect(p.getByRole('dialog')).toBeHidden();
  await expect(p.getByTestId('model-time')).toHaveText((captured.playhead/10000).toFixed(3)+' s');await expect(p.getByTestId('recorded-frontier')).toHaveText('Recorded to '+(captured.frontier/10000).toFixed(3)+' s');await expect(p.getByTestId('replay-status')).toHaveText('Not checked');await expect(p.getByTestId('save-status')).toHaveText('Saved');
  const download=p.waitForEvent('download');await click(p,'Export file');const restored=JSON.parse(readFileSync(await(await download).path(),'utf8')).content;
  expect(restored.metadata.id).toBe(captured.metadata.id);for(const key of ['seed','playhead','frontier','forkTick','recordRevision','anchor','snapshots','live','records'])expect(restored[key]).toEqual(captured[key]);entry.contract.reopenedSameState=true;entry.status='NEW_PASS';
  const cdp=await ctx.newCDPSession(p);await cdp.send('Performance.enable');entry.heap=(await cdp.send('Performance.getMetrics')).metrics.filter(x=>['JSHeapUsedSize','JSHeapTotalSize'].includes(x.name));
  await p.screenshot({path:file(label+'.png')});
 }catch(e){entry.status='FAIL';entry.error=e.stack;report.failures.push({label,error:e.stack});try{entry.firstFailure=await snap(p);await p.screenshot({path:file(label+'-failure.png')})}catch{}}
 finally{report.scenarios.push(entry);put(label+'.json',entry);await ctx.close()}
}
await browser.close();const info=JSON.parse(readFileSync(resolve(distArg,'build-info.json'),'utf8'));const js=Object.keys(info.payload).filter(x=>x.endsWith('.js')).map(path=>{const b=readFileSync(resolve(distArg,path));return{path,decodedBytes:b.length,gzipBytes:gzipSync(b).length}});report.payload={js,jsGzipBytes:js.reduce((a,x)=>a+x.gzipBytes,0),firstContextRequests:report.requests,rawApiBodySumNotWire:report.requests.reduce((a,r)=>a+(r.sizes?.responseBodySize??0),0),conservativeContentLengthBytes:report.requests.reduce((a,r)=>a+(Number(r.headers['content-length'])||0),0),transferHeadersBytes:report.requests.reduce((a,r)=>a+(r.sizes?.responseHeadersSize??0),0),note:'Worker API sizes may be zero/negative; raw sum is not full wire transfer. gzip is explicit local compression size; content-length is a conservative body bound. Requests include Guide on first cold context; not a throttled-network latency benchmark.'};
if(report.normal)report.normal.gates={fps:report.normal.fps>=55,p95:report.normal.frameSummary.p95<=20,throughput:report.normal.commonModelSecondsPerSecond>=1,visible:report.normal.after.visible==='visible',active:report.normal.after.active,gpuIsM4:report.normal.after.gpu.some(x=>x.renderer.includes('Apple M4 Pro'))};
put('result.json',report);console.log(JSON.stringify({out,normal:report.normal&&{fps:report.normal.fps,p95:report.normal.frameSummary.p95,throughput:report.normal.commonModelSecondsPerSecond,gates:report.normal.gates},scenarios:report.scenarios.map(s=>({label:s.label,status:s.status,error:s.error})),failures:report.failures}));
