import { expect, it } from 'vitest';
import { accessibleCells, branchMetrics, divergence, interventionCost } from './metrics';
import { createInitialState } from '../simulation/engine';
import type { InterventionEvent } from '../experiments/events';
const event = { id: 'e', branch: 'A', model: 'test', datasetHash: 'test', configHash: 'test', operatorVersion: 1, operation: 'suppression', sourceIds: ['1', '2'], sensoryChannel: null, magnitude: .5, startTick: 0, endTick: 100, sequence: 1 } satisfies InterventionEvent;
it('uses shared body samples, actual path, geometrical proximity and hand-calculated time/scope cost', () => {
    const a = createInitialState(1), b = createInitialState(1);
    a.tick = b.tick = 200;
    a.trail = [{ tick: 0, x: 20, y: 66, heading: 0 }, { tick: 100, x: 23, y: 66, heading: 0 }, { tick: 200, x: 23, y: 70, heading: 0 }];
    b.trail = a.trail.map(p => ({ ...p, x: p.x + 3, y: p.y + 4 }));
    const samples = [{ tick: 100, leftHz: 100, rightHz: 300, ratio: 1, speed: 6, turn: 1.5, displacement: 3, blocked: false }, { tick: 200, leftHz: 100, rightHz: 100, ratio: .5, speed: 3, turn: 0, displacement: 0, blocked: true }];
    const m = branchMetrics(a, samples, [event], 0, 200)!;
    expect(m.path).toBe(7);
    expect(m.capFraction).toBe(.5);
    expect(m.capSeconds).toBe(.01);
    expect(m.stallFraction).toBe(.5);
    expect(m.stallSeconds).toBe(.01);
    expect(m.leftHz).toBe(100);
    expect(m.rightHz).toBe(200);
    expect(m.rawSpeed).toBe(4.5);
    expect(m.pnDifference).toBe(100);
    expect(m.cost).toBe(.5 * 2 / 8 * .5);
    expect(m.proximity).toBe(1 - (Math.hypot(23 - 28, 70 - 10) - 3) / Math.hypot(40, 80));
    expect(divergence(a, b, 0, 200)).toBe(5 / Math.hypot(40, 80));
    expect(accessibleCells().has('20,66')).toBe(true);
    expect(accessibleCells().has('0,0')).toBe(false);
    expect(interventionCost([{ ...event, operation: 'odor-gain', sourceIds: [], sensoryChannel: 'odor', magnitude: 0 }], 0, 200, 8)).toBe(.5);
});
it('zero, unequal or missing windows are unavailable; future goals/samples are not reported', () => {
    const a = createInitialState(1), b = createInitialState(2);
    expect(branchMetrics(a, [], [], 0, 0)).toBeNull();
    expect(divergence(a, b, 0, 0)).toBeNull();
    b.tick = 100;
    expect(divergence(a, b, 0, 100)).toBeNull();
    expect(branchMetrics(a, [], [], 0, 100)).toBeNull();
    a.tick = 200;
    a.trail.push({ tick: 100, x: 20, y: 65, heading: 0 }, { tick: 200, x: 20, y: 64, heading: 0 });
    a.goalReachedTick = 200;
    const m = branchMetrics(a, [{ tick: 100, leftHz: 1, rightHz: 1, ratio: .005, speed: .03, turn: 0, displacement: 1, blocked: false }], [], 0, 100)!;
    expect(m.goalTick).toBeNull();
    expect(m.path).toBe(1);
});
it('tiny positive command with zero representable displacement is not labelled a collision', () => {
    const a = createInitialState(1);
    a.tick = 100;
    a.trail.push({ ...a.trail[0], tick: 100 });
    const samples = [{ tick: 100, leftHz: 1e-200, rightHz: 1e-200, ratio: 5e-203, speed: 3e-202, turn: 0, displacement: 0, blocked: false }];
    expect(branchMetrics(a, samples, [], 0, 100)!.stallFraction).toBe(0);
});
